### ISSUE TITLE
Como sobrescrever  o layout ?

### ISSUE THREAD

**Issue by lucasmendonca** [CakePHPBrasil/TwitterBootstrap#7]
Gostaria de sobrescrever o layout adminlte.ctp assim como consigo sobrescrever os elements.

Por exemplo, para editar o template preciso editar o arquivo vendor/cakephp-brasil/src/Template/Layout/adminlte.ctp 

Já tentei criar um arquivo adminlte.ctp  em src/Template/Element/adminlte ou src/Layout, mas sem sucesso.

É possível sobrescrever o layout do plugin assim como é possível sobrescrever os elements ?

**Comment by erikfig** [comment]
Então @lucasmendonca, você não precisa sobrescrever, é só criar o layout no diretório de layouts do cake e setar ```$this->viewBuilder()->layout('SeuLayout');``` em vez de ```$this->viewBuilder()->theme('TwitterBootstrap');```

Isso deve resolver

**Comment by lucasmendonca** [comment]
Perfeito! Obrigado!
